services:
  run:
    build: .
    env_file:
      - path: .env
        required: false

  serve:
    build: .
    command: ["serve"]
    ports:
      - "8080:8080"
    env_file:
      - path: .env
        required: false
